require 'faker'

User.destroy_all
BookCollection.destroy_all 
Follow.destroy_all
UserBook.destroy_all

puts 'seeding users'

User.create(name: 'Dana', grade: 'second grade teacher', email: 'danalobell@gmail.com', username: 'msdana', password: 'abc')
User.create(name: 'Emily', grade: 'first grade teacher', email: 'emily@gmail.com', username: 'msemily', password: 'abc')
User.create(name: 'Tom', grade: 'kindergarten teacher', email: 'tom@gmail.com', username: 'mrtom', password: 'abc')
User.create(name: 'Jake', grade: 'third grade teacher', email: 'jake@gmail.com', username: 'mrjake', password: 'abc')
User.create(name: 'Brittney', grade: 'second grade teacher', email: 'brittney@gmail.com', username: 'msbrittney', password: 'abc')
User.create(name: 'Sage', grade: 'first grade teacher', email: 'sage@gmail.com', username: 'mssage', password: 'abc')
User.create(name: 'Zak', grade: 'third grade teacher', email: 'zak@gmail.com', username: 'mrzak', password: 'abc')
User.create(name: 'Tony', grade: 'third grade teacher', email: 'tony@gmail.com', username: 'mrtony', password: 'abc')
User.create(name: 'John', grade: 'kindergarten teacher', email: 'john@gmail.com', username: 'mrjohn', password: 'abc')
User.create(name: 'Maisy', grade: 'second grade teacher', email: 'maisy@gmail.com', username: 'msmaisy', password: 'abc')

puts 'users seeded'

puts 'book collection seeding'

BookCollection.create(title: 'Girls Who Code', author: 'Jo Whittemore', subject: 'Girls in Tech', image: 'https://images4.penguinrandomhouse.com/cover/9780399542534', banned: true, link: "https://cafeconlibrosbooks.indielite.org/book/9780399542534", description: "Maya and her friends from coding club have an exciting new project: they're coding lights and music for the winter dance! But when Maya's old troublemaking friend Maddie moves to town, Maya starts spending a lot of time with her, and less time with her coding friends. Maddie just gets her in a way that her other friends don't. Will Maya get swayed by Maddie's wayward ways, or will she stay true to her 'permanent group' from coding club? And will she come through on her part for the light and music coding project? Maybe coding--like friendship--is about being there for your friends when they need you the most.")
BookCollection.create(title: 'This Day in June', author: 'Gayle Pitman', subject: 'LGBTQIA+', image: 'https://www.epl.org/wp-content/uploads/2021/09/this-day-in-june.jpg', banned: true, link: "https://cafeconlibrosbooks.indielite.org/book/9781433816581", description: "In a wildly whimsical, validating, and exuberant reflection of the LGBTQ+ community, This Day In June welcomes readers to experience a pride celebration and share in a day when we are all united. Also included is a Note to Parents and Other Caregivers with information on how to talk to children about sexual orientation and gender identity in age-appropriate ways as well as a Reading Guide chock-full of facts about LGBTQ+ history and culture. This Day in June is an excellent tool for teaching respect, acceptance, and understanding of lesbian, gay, bisexual, and transgender people.")
BookCollection.create(title: 'The Family Book', author: 'Todd Parr', subject: 'Families', image: 'https://www.toddparr.com/wp-content/uploads/2020/07/9780316187107-1.jpg?fit=450%2C450', banned: true, link: "https://cafeconlibrosbooks.indielite.org/book/9780316070409", description: "The Family Book celebrates the love we feel for our families and all the different varieties they come in. Whether you have two moms or two dads, a big family or a small family, a clean family or a messy one, Todd Parr assures readers that no matter what kind of family you have, every family is special in its own unique way.")
BookCollection.create(title: 'Drama', author: 'Raina Telgemeier', subject: 'LGBTQIA+', image: 'https://images.squarespace-cdn.com/content/v1/5a2495ad8a02c7c08b0dcc3f/1513476639170-W3KXNQD7TTD2GK4CY56W/DRAMA_cover_shadow.jpg?format=1000w', banned: true, link: "https://cafeconlibrosbooks.indielite.org/book/9780545326995", description: "Callie loves theater. And while she would totally try out for her middle school's production of Moon over Mississippi, she can't really sing. Instead she's the set designer for the drama department's stage crew, and this year she's determined to create a set worthy of Broadway on a middle-school budget. But how can she, when she doesn't know much about carpentry, ticket sales are down, and the crew members are having trouble working together? Not to mention the onstage AND offstage drama that occurs once the actors are chosen. And when two cute brothers enter the picture, things get even crazier!")
BookCollection.create(title: 'Saffron Ice Cream', author: 'Rashin Kheiriyeh', subject: 'Middle Eastern', image: 'https://embed.cdn.pais.scholastic.com/v1/channels/tso/products/identifiers/isbn/9781338150520/primary/renditions/700', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781338150520", description: "Rashin is excited about her first visit to the beach in her family's new home. On the way there, she remembers what beach trips were like in Iran, the beautiful Caspian Sea, the Persian music, and most of all, the saffron ice cream she shared with her best friend, Azadeh. But there are wonderful things in this new place as well -- a subway train, exciting music... and maybe even a new friend!")
BookCollection.create(title: 'When I Coloured in the World', author: 'Ahmadreza Ahmadi', subject: 'Middle Eastern', image: 'https://tinyowl.co.uk/wp-content/uploads/2017/01/WICW-new-coverLR-600x599.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781910328224", description: "Click on the I want it to learn more!")
BookCollection.create(title: 'The Secret Message', author: 'Mina Javaherbin', subject: 'Middle Eastern', image: 'https://minajavaherbin.net/wp-content/uploads/2019/10/secretmessage.jpg', banned: false, link: "https://www.amazon.com/Secret-Message-Mina-Javaherbin/dp/1423110447/ref=sr_1_1?crid=1YCTLO33726IP&keywords=the+secret+message&qid=1666651932&qu=eyJxc2MiOiIwLjU2IiwicXNhIjoiMC41NyIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=the+secret+message%2Caps%2C78&sr=8-1", description: "Alone, imprisoned in a golden cage, and far from the jungles of home, a parrot longs to escape. Will he ever fly free again? Based on a poem by the ancient Persian philosopher Rumi, The Secret Message is a funny story of surprising twists, powerful solidarity, exotic travels, and a simple wish fulfilled. This witty tale, told with humor and vibrant images, will enchant young readers as it introduces them to the culture, literature, and history of Persia.")
BookCollection.create(title: "It Ain't So Awful, Falafel", author: 'Firoozeh Dumas', subject: 'Middle Eastern', image: 'https://prodimage.images-bn.com/lf?set=key%5Bresolve.pixelRatio%5D,value%5B1%5D&set=key%5Bresolve.width%5D,value%5B600%5D&set=key%5Bresolve.height%5D,value%5B10000%5D&set=key%5Bresolve.imageFit%5D,value%5Bcontainerwidth%5D&set=key%5Bresolve.allowImageUpscaling%5D,value%5B0%5D&set=key%5Bresolve.format%5D,value%5Bwebp%5D&source=url%5Bhttps://prodimage.images-bn.com/pimages/9781328740960_p0_v4_s600x595.jpg%5D&scale=options%5Blimit%5D,size%5B600x10000%5D&sink=format%5Bwebp%5D', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781328740960", description: "It's the late 1970s, and fitting in becomes more difficult as Iran makes U.S. headlines with protests, revolution, and finally the taking of American hostages. Even puka shell necklaces, pool parties, and flying fish can't distract Cindy from the anti-Iran sentiments that creep way too close to home.")
BookCollection.create(title: 'The Green Musician', author: 'Mahvash Shahegh', subject: 'Middle Eastern', image: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1438813991l/25721005.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781937786427", description: "If you had just one chance to achieve your dream, what would you do? In a distant kingdom lived a young musician named Barbad. His one dream was to play before the king in the royal court. But Barbad's way was blocked by Sarkash, a jealous rival who would do anything to stop Barbad from meeting the king. ")
BookCollection.create(title: 'Persepolis: The Story of a Childhood', author: 'Marjane Satrapi', subject: 'Middle Eastern', image: 'https://s39361.pcdn.co/wp-content/uploads/2017/03/9780375714573-persopolis-203x300.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780375714573", description: "In powerful black-and-white comic strip images, Satrapi tells the coming-of-age story of her life in Tehran from ages six to fourteen, years that saw the overthrow of the Shah's regime, the triumph of the Islamic Revolution, and the devastating effects of war with Iraq. The intelligent and outspoken only child of committed Marxists and the great-granddaughter of one of Iran’s last emperors, Marjane bears witness to a childhood uniquely entwined with the history of her country.")
BookCollection.create(title: 'The Colors of Us', author: 'Karen Katz', subject: 'Celebrating Skin Color', image: 'https://mpd-biblio-covers.imgix.net/9780805071634.jpg?w=300', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780805071634", description: "Seven-year-old Lena is going to paint a picture of herself. She wants to use brown paint for her skin. But when she and her mother take a walk through the neighborhood, Lena learns that brown comes in many different shades.")
BookCollection.create(title: 'All the Colors We Are: The Story of How We Get Our Skin Color', author: 'Katie Kissinger', subject: 'Celebrating Skin Color', image: 'https://s39361.pcdn.co/wp-content/uploads/2017/04/9781605540795_all-the-colors-we-are-300x232.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781605540795", description: "Celebrate the essence of one way we are all special and different from one another--our skin color This bilingual (English/Spanish) book offers children a simple, scientifically accurate explanation about how our skin color is determined by our ancestors, the sun, and melanin.")
BookCollection.create(title: 'The Skin You Live In', author: 'Michael Tyler', subject: 'Celebrating Skin Color', image: 'https://images.squarespace-cdn.com/content/v1/5beb22573917ee0ad11974b0/1594318676951-8VPMZGTQFJ34S9JU7FCB/CCM-SkinYouLiveIn.cov-72d.RGB.jpg?format=750w', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780975958001", description: "With the ease and simplicity of a nursery rhyme, this lively story delivers an important message of social acceptance to young readers. Themes associated with child development and social harmony, such as friendship, acceptance, self-esteem, and diversity are promoted in simple and straightforward prose.")
BookCollection.create(title: 'Skin Again', author: 'Bell Hooks', subject: 'Celebrating Skin Color', image: 'https://bellhooksbooks.com/wp-content/uploads/2018/08/Skin-Again-500.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781484799239", description: "Race matters, but only so much--what's most important is who we are on the inside. Looking beyond skin, going straight to the heart, we find in each other the treasures stored down deep. Learning to cherish those treasures, to be all we imagine ourselves to be, makes us free.")
BookCollection.create(title: 'Shades of People', author: 'Shelley Rotner', subject: 'Celebrating Skin Color', image: 'https://www.shelleyrotner.com/admin/wp-content/uploads/2011/10/shades-cover.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780823423057", description: "A celebration of the diversity of everyday life, this exploration of one of our most noticeable physical traits pairs simple text with vibrant photographs.  At school, at the beach, and in the city, diverse groups of children invite young readers both to take notice and to look beyond the obvious.")
BookCollection.create(title: 'Pretty Melanin Me!', author: 'Markita Richards', subject: 'Celebrating Skin Color', image: 'https://www.afriwarebooks.com/uploads/1/6/3/7/16375858/s205239500165048604_p3032_i1_w1037.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780578458052", description: "Click I want it to learn more!")
BookCollection.create(title: 'Skin Like Mine', author: 'LaTashia M. Perry', subject: 'Celebrating Skin Color', image: 'https://mijabooks.com/wp-content/uploads/2020/12/Skin-Like-Mine.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780997157987", description: "Social Themes - Self-Esteem & Self-Reliance")
BookCollection.create(title: 'More Than Peach', author: 'Bellen Woodard', subject: 'Celebrating Skin Color', image: 'https://embed.cdn.pais.scholastic.com/v1/channels/clubs-us/products/identifiers/isbn/9781338863147/primary/renditions/900', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781338809275", description: "When Bellen Woodard's classmates referred to 'the skin-color' crayon, in a school and classroom she had always loved, she knew just how important it was that everyone understood that 'skin can be any number of beautiful colors.' This stunning picture book spreads Bellen's message of inclusivity, empowerment, and the importance of inspiring the next generation of leaders. Bellen created the More Than Peach Project and crayons with every single kid in mind to transform the crayon industry and grow the way we see our world. And Bellen has done just that!")
BookCollection.create(title: 'Skin we are in', author: 'Sindiwe Magona & Nina G. Jablonski', subject: 'Celebrating Skin Color', image: 'https://prodimage.images-bn.com/lf?set=key%5Bresolve.pixelRatio%5D,value%5B1%5D&set=key%5Bresolve.width%5D,value%5B600%5D&set=key%5Bresolve.height%5D,value%5B10000%5D&set=key%5Bresolve.imageFit%5D,value%5Bcontainerwidth%5D&set=key%5Bresolve.allowImageUpscaling%5D,value%5B0%5D&set=key%5Bresolve.format%5D,value%5Bwebp%5D&source=url%5Bhttps://prodimage.images-bn.com/pimages/9781485624899_p0_v1_s600x595.jpg%5D&scale=options%5Blimit%5D,size%5B600x10000%5D&sink=format%5Bwebp%5D', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781485624899", description: "Click I want it to learn more!")
BookCollection.create(title: 'Happy in Our Skin', author: 'Fran Manushkin', subject: 'Celebrating Skin Color', image: 'https://cdn.booktrust.org.uk/globalassets/images/book-jackets/h/happy-in-our-skin.jpg?preset=book_large&anchor=middlecenter', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780763699727", description: "Is there anything more splendid than a baby’s skin? Cocoa-brown, cinnamon, peaches and cream. As children grow, their clever skin does, too, enjoying hugs and tickles, protecting them inside and out, and making them one of a kind. Fran Manushkin’s rollicking text and Lauren Tobia’s delicious illustrations paint a breezy and irresistible picture of the human family — and how wonderful it is to be just who you are.")
BookCollection.create(title: 'Your Name is a Song', author: 'Jamilah Thompkins-Bigelow', subject: 'African, African American', image: 'https://images.squarespace-cdn.com/content/v1/5734ec209f7266f8a847dc52/1574362869789-VGD4XOGP5C488BWPDU70/Your_Name-is-a-Song-Oversized_Jacket-New-Artwork-Sept2019.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781943147724", description: "Frustrated by a day full of teachers and classmates mispronouncing her beautiful name, a little girl tells her mother she never wants to come back to school. In response, the girl's mother teaches her about the musicality of African, Asian, Black-American, Latinx, and Middle Eastern names on their lyrical walk home through the city. ")
BookCollection.create(title: 'Not So Fast, Songololo', author: 'Niki Daly', subject: 'African, African American', image: 'https://www.publishersweekly.com/cover/9780689503672', banned: false, link: "https://www.amazon.com/Not-Fast-Songololo-Niki-Daly/dp/0689503679/ref=sr_1_1?keywords=not+so+fast+songolo&qid=1666652519&qu=eyJxc2MiOiIwLjY3IiwicXNhIjoiMC40MCIsInFzcCI6IjAuNDEifQ%3D%3D&sprefix=not+so+fast+song%2Caps%2C77&sr=8-1", description: "The setting is South Africa and the names of the people are like poetry: Uzuti, Mongi, Mr. Motiki. Malusi is now old enough to accompany his grandmother, Gogo, into the city to shop. She is an old womanample, proud, not quite in step with modern technology, and she is no longer moves quickly. Malusi (Songololo to his grandmother) helps her with her shopping. It's a universally appealing shared experience. ")
BookCollection.create(title: 'The Water Princess', author: 'Susan Verde', subject: 'African, African American', image: 'https://images3.penguinrandomhouse.com/cover/9780399172588', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9787559804174", description: "Fairy Tales & Folklore")
BookCollection.create(title: 'Emmanuel’s Dream: The True Story of Emmanuel Ofosu', author: 'Laurie Ann Thompson', subject: 'African, African American', image: 'https://s39361.pcdn.co/wp-content/uploads/2017/03/9780449817445-Emmanuels-Dream.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780449817445", description: "Born in Ghana, West Africa, with one deformed leg, he was dismissed by most people—but not by his mother, who taught him to reach for his dreams. As a boy, Emmanuel hopped to school more than two miles each way, learned to play soccer, left home at age thirteen to provide for his family, and, eventually, became a cyclist. He rode an astonishing four hundred miles across Ghana in 2001, spreading his powerful message: disability is not inability. Today, Emmanuel continues to work on behalf of the disabled.")
BookCollection.create(title: 'Make Way for Dyamonde Daniel', author: 'Nikki Grimes', subject: 'African, African American', image: 'https://images4.penguinrandomhouse.com/cover/9780142415559', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780142415559", description: "Dyamonde Daniel may be new in town, but that doesn't stop her from making a place for herself in a jiffy. With her can-do attitude and awesome brain power she takes the whole neighborhood by storm. The only thing puzzling her is the other new kid in her class. He's grouchy - but Dyamonde's determined to get to the bottom of his attitude and make a friend.")
BookCollection.create(title: 'The Snowy Day', author: 'Ezra Jack Keats', subject: 'African, African American', image: 'https://www.ezra-jack-keats.org/wp-content/uploads/2013/12/The_Snowy_Day_Book_Cover.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780670867332", description: "The magic and wonder of winter’s first snowfall is perfectly captured in Ezra Jack Keat’s Caldecott Medal-winning picture book. This celebrated classic has been shared by generations of readers and listeners, a must-have for every child’s bookshelf and a perfect gift for the holiday season.")
BookCollection.create(title: 'One Plastic Bag: Isatou Ceesay and the Recycling Women of the Gambia', author: 'Miranda Paul', subject: 'African, African American', image: 'http://oneplasticbag.com/wp-content/uploads/2014/10/One_Plastic_Bag_Cover_Miranda_Paul1-300x253.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781467716086", description: "The inspiring true story of how one African woman began a movement to recycle the plastic bags that were polluting her community.")
BookCollection.create(title: 'Gogo’s List', author: 'Portia Dery', subject: 'African, African American', image: 'https://jacana.co.za/wp-content/uploads/2021/02/GOGOS-LIST-COV-ENG-HR-RGB-1-scaled.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781431428502", description: "Fatima is a young girl who is determined to save the day. She wants to help Gogo with her to-do list so that everyone will realise that she is a big girl now! But things don’t go exactly as expected ... Fatima, what have you done?")
BookCollection.create(title: "Stacey's Extraordinary Words", author: 'Stacey Abrams', subject: 'African, African American', image: 'https://d1ldy8a769gy68.cloudfront.net/300/978/006/320/947/3/9780063209473.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780063209473", description: "Stacey Abrams shares her lifelong love of words, perfectly capturing the excitement—and fear--that come with spelling bee competition, and teaches young readers that winning isn't the most important thing.")
BookCollection.create(title: 'Glow', author: 'Ruth Forman', subject: 'African, African American', image: 'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781534446335/glow-9781534446335_lg.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781534446335", description: "This simple, playful, and elegant board book stars a young boy who joyfully celebrates his dark skin with a bright moon at the end of a perfect day.")
BookCollection.create(title: 'Fry Bread: A Native American Family Story', author: 'Kevin Noble Maillard', subject: 'American Indian', image: 'https://mpd-biblio-covers.imgix.net/9781626727465.jpg?w=900', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781626727465", description: "Told in lively and powerful verse by debut author Kevin Noble Maillard, Fry Bread is an evocative depiction of a modern Native American family, vibrantly illustrated by Pura Belpre Award winner and Caldecott Honoree Juana Martinez-Neal.")
BookCollection.create(title: 'We Are Water Protectors', author: 'Carole Lindstrom', subject: 'American Indian', image: 'https://mpd-biblio-covers.imgix.net/9781250203557.jpg?w=900', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781250203557", description: "When a black snake threatens to destroy the Earth and poison her people's water, one young water protector takes a stand to defend Earth's most sacred resource.")
BookCollection.create(title: 'Classified: The Secret Career of Mary Golda Ross, Cherokee Aerospace Engineer', author: 'Traci Sorell', subject: 'American Indian', image: 'https://s39361.pcdn.co/wp-content/uploads/2021/11/Classified.png', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781666508673", description: "Biography & Autobiography - Science & Technology")
BookCollection.create(title: 'Jo Jo Makoons: The Used-To-Be Best Friend', author: 'Dawn Quigley', subject: 'American Indian', image: 'https://images-us.bookshop.org/ingram/9780063015388.jpg?height=500&v=v2', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780063015388", description: "Jo Jo Makoons Azure is a spirited seven-year-old who moves through the world a little differently than anyone else on her Ojibwe reservation. It always seems like her mom, her kokum (grandma), and her teacher have a lot to learn—about how good Jo Jo is at cleaning up, what makes a good rhyme, and what it means to be friendly.")
BookCollection.create(title: 'Sharice’s Big Voice: A Native Kid Becomes a Congresswoman', author: 'Sharice Davids & Nancy K. Mays', subject: 'American Indian', image: 'https://s39361.pcdn.co/wp-content/uploads/2021/09/Sharices-Big-Voice_large-300x245.png', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780062979667", description: "When Sharice Davids was young, she never thought she’d be in Congress. And she never thought she’d be one of the first Native American women in Congress. During her campaign, she heard from a lot of doubters. They said she couldn’t win because of how she looked, who she loved, and where she came from.")
BookCollection.create(title: 'When the Shadbush Blooms', author: 'Carla Messinger & Susan Katz', subject: 'American Indian', image: 'https://pictures.abebooks.com/isbn/9781582461922-us.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781643792019", description: "A young Lenape Indian girl observes and reflects on the small, important ways her family today, and her ancestors generations before, celebrate the cycle of seasons.")
BookCollection.create(title: 'Young Water Protectors: A Story About Standing Rock', author: 'Aslan Tudor & Kelly Tudor', subject: 'American Indian', image: 'https://s39361.pcdn.co/wp-content/uploads/2021/08/Young-Water-Protectors-232x300.png', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781723305689", description: "A few months later he returned - and saw the whole world watching. Read about his inspiring experiences in the Oceti Sakowin Camp at Standing Rock. Learn about what exactly happened there, and why. Be inspired by Aslan's story of the daily life of Standing Rock's young water protectors. Mni Wiconi ... Water is Life.")
BookCollection.create(title: 'We Are Still Here!: Native American Truths Everyone Should Know', author: 'Traci Sorell', subject: 'American Indian', image: 'https://images-us.bookshop.org/ingram/9781623541927.jpg?height=500&v=v2', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781623541927", description: "Twelve Native American kids present historical and contemporary laws, policies, struggles, and victories in Native life, each with a powerful refrain: We are still here!")
BookCollection.create(title: 'When I Was Eight', author: 'Christy Jordan-Fenton & Margaret Pokiak-Fenton', subject: 'American Indian', image: 'https://s39361.pcdn.co/wp-content/uploads/2017/11/When-I-Was-Eight-9781554514915.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781554514908", description: "Bestselling memoir Fatty Legs for younger readers. Olemaun is eight and knows a lot of things. But she does not know how to read. Ignoring her father's warnings, she travels far from her Arctic home to the outsiders' school to learn. The nuns at the school call her Margaret. They cut off her long hair and force her to do menial chores, but she remains undaunted. Her tenacity draws the attention of a black-cloaked nun who tries to break her spirit at every turn. But the young girl is more determined than ever to learn how to read. ")
BookCollection.create(title: 'This Land Is My Land', author: 'George Littlechild', subject: 'American Indian', image: 'https://s39361.pcdn.co/wp-content/uploads/2019/10/This-Land-is-My-Land.png', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780892391844", description: "Through his own words and paintings, acclaimed Native artist George Littlechild takes us back in time to the first meeting between his Plains Cree ancestors and the first European settlers in North America.")
BookCollection.create(title: 'My Name Is Yoon', author: 'Helen Recorvits', subject: 'Asian American & Pacific Islander', image: 'https://mpd-biblio-covers.imgix.net/9781250057112.jpg?w=900', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781250057112", description: "Helen Recorvits's spare and inspiring story about a little girl finding her place in a new country is given luminous pictures filled with surprising vistas and dreamscapes by Gabi Swiatkowska.")
BookCollection.create(title: 'Alvin Ho: Allergic to Babies, Burglars, and Other Bumps in the Night', author: 'Lenore Look', subject: 'Asian American & Pacific Islander', image: 'https://images3.penguinrandomhouse.com/cover/9780385386005', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780385386005", description: "Alvin becomes a big brother in the fifth book in the hilarious chapter book series that tackles anxiety in a fun, kid-friendly way. Perfect for both beginning and reluctant readers, and fans of Diary of a Wimpy Kid!")
BookCollection.create(title: 'Danbi Leads the School Parade', author: 'Anna Kim', subject: 'Asian American & Pacific Islander', image: 'https://images2.penguinrandomhouse.com/cover/9780451478894', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780451478894", description: "Danbi Leads the School Parade introduces readers to an irresistible new character. In this first story, she learns to navigate her two cultures and realizes that when you open your world to others, their world opens up to you.")
BookCollection.create(title: 'How to Solve a Problem', author: 'Ashima Shiraishi', subject: 'Asian American & Pacific Islander', image: 'https://images1.penguinrandomhouse.com/cover/9781524773274', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781524773274", description: "From Ashima Shiraishi, one of the world's youngest and most skilled climbers, comes a true story of strength and perseverance--in rock climbing and in life.")
BookCollection.create(title: 'My Day with Gong Gong', author: 'Sennah Yee', subject: 'Asian American & Pacific Islander', image: 'https://prodimage.images-bn.com/lf?set=key%5Bresolve.pixelRatio%5D,value%5B1%5D&set=key%5Bresolve.width%5D,value%5B600%5D&set=key%5Bresolve.height%5D,value%5B10000%5D&set=key%5Bresolve.imageFit%5D,value%5Bcontainerwidth%5D&set=key%5Bresolve.allowImageUpscaling%5D,value%5B0%5D&set=key%5Bresolve.format%5D,value%5Bwebp%5D&source=url%5Bhttps://prodimage.images-bn.com/pimages/9781773214283_p0_v2_s600x595.jpg%5D&scale=options%5Blimit%5D,size%5B600x10000%5D&sink=format%5Bwebp%5D', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781773214290", description: "A day in Chinatown takes an unexpected turn when a bored little girl makes a connection with her grandpa.")
BookCollection.create(title: 'Ohana Means Family', author: 'Ilima Loomis', subject: 'Asian American & Pacific Islander', image: 'https://images4.penguinrandomhouse.com/cover/9780823451180', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780823451180", description: "Join the family, or ohana, as they farm taro for poi to prepare for a traditional luau celebration with a poetic text in the style of The House That Jack Built. ")
BookCollection.create(title: "Shark Lady: The True Story of How Eugenie Clark Became the Ocean's Most Fearless Scientist", author: 'Jess Keating', subject: 'Asian American & Pacific Islander', image: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/themes/1937729/settings_images/tuYRx2Q8SKObYNUwwNA8_SharkLadyFinalCoverSmall.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781492642046", description: "This is the story of a woman who dared to dive, defy, discover, and inspire. This is the story of Shark Lady. One of the best science picture books for children, Shark Lady is a must for both teachers and parents alike!")
BookCollection.create(title: 'Asian Americans Who Inspire Us', author: 'Analiza Wolf', subject: 'Asian American & Pacific Islander', image: 'https://images-us.bookshop.org/ingram/9780578578156.jpg?height=500&v=v2', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780578578156", description: "Named to the Gold House Book List, Asian Americans Who Inspire Us introduces readers of all ages to 16 Asian Americans who changed the world.")
BookCollection.create(title: 'Measuring Up', author: 'Lily LaMotte', subject: 'Asian American & Pacific Islander', image: 'https://cdn.teachingbooks.net/content/ingram_images_hi/8/0062973878.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780062973863", description: "A really cute graphic novel about a girl who moves from Taiwan to Seattle.")
BookCollection.create(title: 'Eyes that Kiss in the Corners', author: 'Joanna Ho', subject: 'Asian American & Pacific Islander', image: 'https://prodimage.images-bn.com/lf?set=key%5Bresolve.pixelRatio%5D,value%5B1%5D&set=key%5Bresolve.width%5D,value%5B600%5D&set=key%5Bresolve.height%5D,value%5B10000%5D&set=key%5Bresolve.imageFit%5D,value%5Bcontainerwidth%5D&set=key%5Bresolve.allowImageUpscaling%5D,value%5B0%5D&set=key%5Bresolve.format%5D,value%5Bwebp%5D&source=url%5Bhttps://prodimage.images-bn.com/pimages/9780062915627_p0_v3_s600x595.jpg%5D&scale=options%5Blimit%5D,size%5B600x10000%5D&sink=format%5Bwebp%5D', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780062915627", description: "A young Asian girl notices that her eyes look different from her peers'. They have big, round eyes and long lashes. She realizes that her eyes are like her mother’s, her grandmother's, and her little sister's. They have eyes that kiss in the corners and glow like warm tea, crinkle into crescent moons, and are filled with stories of the past and hope for the future.")
BookCollection.create(title: 'Ada Twist, Scientist', author: 'Andrea Beaty', subject: 'Girls in Tech', image: 'https://media.edutopia.org/styles/responsive_300px_original/s3/masters/d7_images/minero-inset4-yabooks-pr.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9786049763878", description: "Click I want it to learn more!")
BookCollection.create(title: 'Ada: My First Ada Lovelace (Little People, Big Dreams)', author: 'Maria Isabel Sanchez Vegara', subject: 'Girls in Tech', image: 'https://cdn.amightygirl.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/y/my_first_ada.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781786032591", description: "As a child, Ada had a big imagination and a talent for mathematics. She grew up in a noble household in England, where she dedicated herself to studying. Her work with the famous inventor, Charles Babbage, on a very early kind of computer made her the world's first computer programmer.")
BookCollection.create(title: 'Mae Among The Stars', author: 'Roda Ahmed', subject: 'Girls in Tech', image: 'https://cdn.amightygirl.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/mae_1.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780062651730", description: "A beautiful picture book for sharing and marking special occasions such as graduation, inspired by the life of the first African American woman to travel in space, Mae Jemison. ")
BookCollection.create(title: 'I Am Marie Curie', author: 'Brad Meltzer', subject: 'Girls in Tech', image: 'https://cdn.amightygirl.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/9/1/912swfl8kwl_1_.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780525555858", description: "The first woman to win a Nobel Prize, physicist and chemist Marie Curie is the 19th hero in the New York Times bestselling picture book biography series about heroes.")
BookCollection.create(title: 'Anne and Her Tower of Giraffes: The Adventurous Life of the First Giraffologist', author: 'Karlin Gray', subject: 'Girls in Tech', image: 'https://cdn.amightygirl.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/t/o/tower_of_giraffes.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781525304958", description: "The remarkable true story of how a young girl's never-wavering fascination with the world's tallest animal leads her to become the first giraffologist: Dr. Anne Innis Dagg.")
BookCollection.create(title: 'The Astronaut With A Song For The Stars: The Story of Dr. Ellen Ochoa', author: 'Julia Finley Mosca', subject: 'Girls in Tech', image: 'https://cdn.amightygirl.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/o/song_for_the_stars.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781943147632", description: "Meet Dr. Ellen Ochoa-a determined space pioneer with a stellar symphony of talents.")
BookCollection.create(title: 'Secret Engineer: How Emily Roebling Built the Brooklyn Bridge', author: 'Rachel Dougherty', subject: 'Girls in Tech', image: 'https://cdn.amightygirl.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/e/secret_engineer_smaller.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781250155320", description: "This is the story of Emily Roebling, the secret engineer behind the Brooklyn Bridge, from author-illustrator Rachel Dougherty.")
BookCollection.create(title: 'Counting on Katherine: How Katherine Johnson Saved Apollo 13', author: 'Helaine Becker', subject: 'Girls in Tech', image: 'https://cdn.amightygirl.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/o/counting_on_katherine.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781250137524", description: "The bold story of Katherine Johnson, an African-American mathematician who worked for NASA during the space race and was depicted in the film Hidden Figures.")
BookCollection.create(title: 'Queen of Physics: How Wu Chien Shiung Helped Unlock the Secrets of the Atom', author: 'Teresa Robeson', subject: 'Girls in Tech', image: 'https://cdn.amightygirl.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/q/u/queen_of_physics.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781454932208", description: "Meet Wu Chien Shiung, famous physicist who overcame prejudice to prove that she could be anything she wanted.")
BookCollection.create(title: 'Wonder', author: 'R.J. Palacio', subject: 'Persons with Disabilities', image: 'https://images-na.ssl-images-amazon.com/images/I/71C7PBhlB9L.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780375869020", description: "R.J. Palacio has called her debut novel “a meditation on kindness” —indeed, every reader will come away with a greater appreciation for the simple courage of friendship. Auggie is a hero to root for, a diamond in the rough who proves that you can’t blend in when you were born to stand out.")
BookCollection.create(title: 'Thank You, Mr. Falker', author: 'Patricia Polacco', subject: 'Persons with Disabilities', image: 'https://images-na.ssl-images-amazon.com/images/I/91-pkhhHBlL.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780399231667", description: "The real-life, classic story of a dyslexic girl and the teacher who would not let her fail. A perfect gift for teachers and for reading students of any age.")
BookCollection.create(title: 'El Deafo', author: 'Cece Bell', subject: 'Persons with Disabilities', image: 'https://images-na.ssl-images-amazon.com/images/I/61FIps1446L.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781419712173", description: "Starting at a new school is scary, especially with a giant hearing aid strapped to your chest! At her old school, everyone in Cece’s class was deaf. Here, she’s different. She’s sure the kids are staring at the Phonic Ear, the powerful aid that will help her hear her teacher. Too bad it also seems certain to repel potential friends.")
BookCollection.create(title: 'Rescue & Jessica: A Life Changing Friendship', author: 'Jessica Kensky', subject: 'Persons with Disabilities', image: 'https://images-na.ssl-images-amazon.com/images/I/91-+ff45LWL.jpg', banned: false, link: "https://www.amazon.com/Rescue-Jessica-Life-Changing-Friendship-Kensky/dp/0763696048/ref=sr_1_1?crid=3AUYU885DYRN7&keywords=Rescue+%26+Jessica%3A+A+Life+Changing+Friendship&qid=1666654077&sprefix=rescue+%26+jessica+a+life+changing+friendship%2Caps%2C176&sr=8-1", description: "Based on a real-life partnership, the heartening story of the love and teamwork between a girl and her service dog will illuminate and inspire.")
BookCollection.create(title: 'Soul Surfer: A True Story of Faith, Family, and Fighting to Get Back on the Board', author: 'Bethany Hamilton', subject: 'Persons with Disabilities', image: 'https://images-na.ssl-images-amazon.com/images/I/71oEbnpczxL.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781416503460", description: "In this moving personal account of faith and fortitude, internationally ranked surfer Bethany Hamilton tells how she survived a shark attack that cost her arm--but not her spirit.")
BookCollection.create(title: 'When Charley Met Emma', author: 'Amy Webb', subject: 'Persons with Disabilities', image: 'https://images-na.ssl-images-amazon.com/images/I/51jfhFtVwiL._SX403_BO1,204,203,200_.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781506448725", description: "This delightful book will help kids think about disability, kindness, and how to behave when they meet someone who is different from them.")
BookCollection.create(title: 'Just Ask: Be Different, Be Brave, Be You', author: 'Sonia Sotomayor', subject: 'Persons with Disabilities', image: 'https://www.rebekahgienapp.com/wp-content/uploads/2022/03/just-ask.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780525514121", description: "Justice Sonia Sotomayor and award-winning artist Rafael Lopez create a kind and caring book about the differences that make each of us unique.")
BookCollection.create(title: 'My Three Best Friends and Me, Zulay', author: 'Cari Best', subject: 'Persons with Disabilities', image: 'https://www.rebekahgienapp.com/wp-content/uploads/2019/12/my_best_friends.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780374388195", description: "Zulay and her three best friends are all in the same first grade class and study the same things, even though Zulay is blind. When their teacher asks her students what activity they want to do on Field Day, Zulay surprises everyone when she says she wants to run a race. With the help of a special aide and the support of her friends, Zulay does just that.")
BookCollection.create(title: 'I Talk Like a River', author: 'Jordan Scott', subject: 'Persons with Disabilities', image: 'https://www.rebekahgienapp.com/wp-content/uploads/2019/12/I_talk_like_river.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780823445592", description: "When a boy who stutters feels isolated, alone, and incapable of communicating in the way he'd like, it takes a kindly father and a walk by the river to help him find his voice. Compassionate parents everywhere will instantly recognize a father's ability to reconnect a child with the world around him.")
BookCollection.create(title: 'My Travelin’ Eye', author: 'Jenny Sue Kostecki-Shaw', subject: 'Persons with Disabilities', image: 'https://www.rebekahgienapp.com/wp-content/uploads/2019/12/my_travelin_eye.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780805081695", description: "Jenny Sue's eyes are not the same as other people's eyes. Her right eye looks in one direction, while her left eye sometimes wanders. Jenny Sue has a travelin', lazy eye. Although it makes her different, it also helps her see the world in a special way.")
BookCollection.create(title: 'The Proudest Blue A Story of Hijab and Family', author: 'Ibtihaj Muhammad with S.K. Ali', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2019/10/The-Proudest-Blue-A-Story-of-Hijab-and-Family-225x225.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780316519007", description: "Paired with Hatem Aly's beautiful, whimsical art, Olympic medalist Ibtihaj Muhammad and Morris Award finalist S.K. Ali bring readers an uplifting, universal story of new experiences, the unbreakable bond between siblings, and of being proud of who you are.")
BookCollection.create(title: 'Mommy’s Khimar', author: 'Jamilah Thompkins-Bigelow', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2020/06/Mommys-Khimar-289x225.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781534400597", description: "A young Muslim girl spends a busy day wrapped up in her mother’s colorful headscarf in this sweet and fanciful picture book from debut author and illustrator Jamilah Tompkins-Bigelow and Ebony Glenn.")
BookCollection.create(title: 'Under My Hijab', author: 'Hena Khan', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2019/03/Under-My-Hijab-271x225.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781620147924", description: "This lovely book from the author of Golden Domes and Silver Lanterns invites readers to understand and appreciate the hijab and the Muslim women who decide to wear it.")
BookCollection.create(title: 'Like the Moon Loves the Sky', author: 'Hena Khan', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2020/03/Like-the-Moon-Loves-the-Sky-715x790.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781452180199", description: "A lyrical and heartwarming celebration of a mother's love for her children by the award-winning author of Golden Domes and Silver Lanterns.")
BookCollection.create(title: 'Halal Hot Dogs', author: 'Susannah Azia', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2021/06/Halal-Hot-Dogs-715x845.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781499811575", description: "Musa has the perfect idea for his special Jummah treat, but things don't go according to plan. Will Musa be able to get a yummy Jummah treat for his family?")
BookCollection.create(title: 'Crescent Moons and Pointed Minarets: A Muslim Book of Shapes', author: 'Hena Khan', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2018/04/Crescent-Moons-and-Pointed-Minarets-A-Muslim-Book-of-Shapes-276x225.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781452182742", description: "Magnificently capturing the shapes of Islam, this acclaimed book that inspired curiosity and conversations about world religions and cultures is now available in paperback.")
BookCollection.create(title: 'The Arabic Quilt: An Immigrant Story', author: 'Aya Khalil', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2020/04/The-Arabic-Quilt-An-Immigrant-Story-715x792.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780884487548", description: "Kanzi’s family has moved from Egypt to America, and on her first day in a new school, what she wants more than anything is to fit in. Maybe that’s why she forgets to take the kofta sandwich her mother has made for her lunch, but that backfires when Mama shows up at school with the sandwich. Mama wears a hijab and calls her daughter Habibti (dear one). When she leaves, the teasing starts.")
BookCollection.create(title: 'One Green Apple', author: 'Eve Bunting', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2016/03/one-green-apple.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780618434770", description: "Ted Lewin’s gorgeous sun-drenched paintings and Eve Bunting’s sensitive text immediately put the reader into another child’s shoes in this timely story of a young Muslim immigrant.")
BookCollection.create(title: 'Malala’s Magic Pencil', author: 'Malala Yousafzai', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2017/11/Malalas-Magic-Pencil.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780316319577", description: "Nobel Peace Prize winner and New York Times bestselling author Malala Yousafzai's first picture book, inspired by her own childhood.")
BookCollection.create(title: 'Amira’s Picture Day', author: 'Reem Faruqi', subject: 'Muslim', image: 'https://imaginationsoup.net/wp-content/uploads/2022/05/Amiras-Picture-Day-715x715.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780823440191", description: "Ramadan has come to an end, and Amira can't wait to stay home from school to celebrate Eid. There's just one hiccup: it's also school picture day. How can Amira be in two places at once?")
BookCollection.create(title: 'Lola Levine meets Jelly and Bean', author: 'Monica Brown', subject: 'Jewish', image: 'http://lolalevine.net/wp-content/uploads/2017/02/lolaJellyBean.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780316258531", description: "The Levines are finally getting a pet--a furry one that is. They are excited about adopting a kitty they name Jelly, but they don't get very far in the process when Ben starts sneezing. Oh no, he's allergic! Lola is devastated and sets out to find Jelly a good home. Luckily, Lola is rewarded with a very happy (and still furry) ending!")
BookCollection.create(title: 'Chik Chak Shabbat', author: 'Mara Rockliff', subject: 'Jewish', image: 'https://www.whatdowedoallday.com/wp-content/uploads/2022/02/jewpb-chik-chak-shabbat.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780763655280", description: "Celebrate Shabbat, community, and diverse traditions with this lyrical tale, illustrated with a lively and whimsical touch.")
BookCollection.create(title: 'A Hat for Mrs.Goldman', author: 'Michelle Edwards', subject: 'Jewish', image: 'https://www.whatdowedoallday.com/wp-content/uploads/2022/02/jewpb-hat-for-mrs-goldman.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780553497106", description: "This heartwarming winter story is perfect for those who love to knit and parents looking to teach their children about the importance of doing good for others!")
BookCollection.create(title: 'Yaffa and Fatima Shalom, Salaam', author: 'Fawzia Gilani-Williams', subject: 'Jewish', image: 'https://www.whatdowedoallday.com/wp-content/uploads/2022/02/jewpb-yaffa.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781467794237", description: "Two neighbors--one Jewish, one Muslim--have always been best friends. When they both fall on hard times, can they find a way to help each other? In Fawzia Gilani's retelling of this folktale--which has both Jewish and Arab origins--differences are not always causes for conflict and friendship can overcome any obstacle.")
BookCollection.create(title: 'The Treasure', author: 'Uri Shulevitz', subject: 'Jewish', image: 'https://www.whatdowedoallday.com/wp-content/uploads/2022/02/jewpb-the-treasure.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780812454048", description: "Isaac's solitary journey, his arrival at hte vast city, and his discovery there are all enriched by Mr. Shulevitz's beautifully detailed illustrations, which masterfully capture the spirit of the original tale while keeping it simple enough for the very youngest reader.")
BookCollection.create(title: 'Bagels from Benny', author: 'Aubrey Davis', subject: 'Jewish', image: 'https://www.whatdowedoallday.com/wp-content/uploads/2022/02/jewpb-bagels-from-benny.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781553377498", description: "Lovingly told, Bagels from Benny explores the values of caring and sharing, building a strong sense of community and finding joy in giving thanks.")
BookCollection.create(title: 'I Dissent: Ruth Bader Ginsburg Makers Her Mark', author: 'Debbie Levy', subject: 'Jewish', image: 'https://www.whatdowedoallday.com/wp-content/uploads/2022/02/i-dissent-book-cover.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781481465595", description: "Get to know celebrated Supreme Court justice Ruth Bader Ginsburg—in the first picture book about her life—as she proves that disagreeing does not make you disagreeable!")
BookCollection.create(title: 'The Book Rescuer', author: 'Sue Macy', subject: 'Jewish', image: 'https://www.whatdowedoallday.com/wp-content/uploads/2020/11/pbold-book-rescuer-1.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781481472203", description: "Told in a folkloric voice reminiscent of Patricia Polacco, this story celebrates the power of an individual to preserve history and culture, while exploring timely themes of identity and immigration.")
BookCollection.create(title: 'You Never Heard of Sandy Koufax?!', author: 'Jonah Winter', subject: 'Jewish', image: 'https://www.whatdowedoallday.com/wp-content/uploads/2022/02/sandy-koufax.jpeg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780553498424", description: "In this striking picture book biography, an old-timer tells us what made Sandy Koufax such an amazing baseball player. ")
BookCollection.create(title: 'Jewish Just Like You', author: 'Kylie Ora Lobell', subject: 'Jewish', image: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51vbcXrVgAL._SX398_BO1,204,203,200_.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9798697156018", description: "'Jewish Just Like You' is the first children's book for the children of Jewish converts. It teaches children to be proud of their Jewish heritage and respect the traditions of both parents' families.")
BookCollection.create(title: "Téo's Tutu", author: 'Maryann Jacob Macias', subject: 'LGBTQIA+', image: 'https://images.randomhouse.com/cover/9781984815521', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781984815521", description: "This story of a boy's first ballet recital celebrates gender-creativity, the joy of dance, and being yourself.")
BookCollection.create(title: 'Born Ready: The True Story of a Boy Named Penelope', author: 'Jodie Patterson', subject: 'LGBTQIA+', image: 'https://images4.penguinrandomhouse.com/cover/9780593123638', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780593123638", description: "Jodie Patterson, activist and Chair of the Human Rights Campaign Foundation Board, shares her transgender son's experience in this important picture book about identity and acceptance.")
BookCollection.create(title: 'I Am Jazz', author: 'Jessica Herthel & Jazz Jenning', subject: 'LGBTQIA+', image: 'https://images1.penguinrandomhouse.com/cover/9780803741072', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780803741072", description: "The story of a transgender child based on the real-life experience of Jazz Jennings, who has become a spokesperson for transkids everywhere.")
BookCollection.create(title: 'Pride: The Story of Harvey Milk and the Rainbow Flag', author: 'Rob Sanders', subject: 'LGBTQIA+', image: 'https://images3.penguinrandomhouse.com/cover/9780399555312', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780399555312", description: "Celebrate Pride and it's iconic rainbow flag--a symbol of inclusion and acceptance around the world-- with the very first picture book to tell its remarkable and inspiring history!")
BookCollection.create(title: 'Prince & Knight', author: 'Daniel Haack', subject: 'LGBTQIA+', image: 'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781499810950/prince-knight-9781499810950_lg.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781499805529", description: "Once upon a time, in a kingdom far from here, there was a prince in line to take the throne, so his parents set out to find him a kind and worthy bride. The three of them traveled the land far and wide, but the prince didn't quite find what he was looking for in the princesses they met.")
BookCollection.create(title: 'Better Nate Than Ever', author: 'Tim Federle', subject: 'LGBTQIA+', image: 'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781534429130/better-nate-than-ever-9781534429130_lg.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781534429130", description: "A small-town boy hops a bus to New York City to crash an audition for E.T.: The Musical in this winning middle grade novel that The New York Times called 'inspired and inspiring.'")
BookCollection.create(title: 'I am Billie Jean King', author: 'Brad Meltzer', subject: 'LGBTQIA+', image: 'https://images3.penguinrandomhouse.com/cover/9780735228740', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780735228740", description: "Billie Jean King is one of the greatest tennis players of all time. Read about this amazing woman athlete in the seventeenth picture book in the New York Times bestselling series of biographies about heroes. ")
BookCollection.create(title: 'Abuelita and I Make Flan', author: 'Adriana Hernández Bergstrom', subject: 'Latinx', image: 'https://s39361.pcdn.co/wp-content/uploads/2022/06/Abuelita-and-I-Make-Flan-241x300.png', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781623542658", description: "Anita loves to bake with her abuela, especially when they are using her grandmother’s special recipes for Cuban desserts like flan!")
BookCollection.create(title: 'Alma and How She Got Her Name', author: 'Juana Martinez-Neal', subject: 'Latinx', image: 'https://s39361.pcdn.co/wp-content/uploads/2018/06/alma.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780763693558", description: "What’s in a name? For one little girl, her very long name tells the vibrant story of where she came from — and who she may one day be.")
BookCollection.create(title: 'Areli Is a Dreamer: A True Story by Areli Morales', author: 'Areli Morales', subject: 'Latinx', image: 'https://images4.penguinrandomhouse.com/cover/9781984893994', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781984893994", description: "In the first picture book written by a DACA Dreamer, Areli Morales tells her own powerful and vibrant immigration story.")
BookCollection.create(title: 'Coquí in the City', author: 'Nomar Perez', subject: 'Latinx', image: 'https://images4.penguinrandomhouse.com/cover/9780593109038', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780593109038", description: "A heartfelt picture book based on the author-illustrator's own experiences, about a boy who moves to the U.S. mainland from Puerto Rico and realizes that New York City might have more in common with San Juan than he initially thought.")
BookCollection.create(title: 'Julián at the Wedding', author: 'Jessica Love', subject: 'Latinx', image: 'https://images2.penguinrandomhouse.com/cover/9781536212389', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781536212389", description: "The star of Julián Is a Mermaid makes a joyful return—and finds a new friend—at a wedding to be remembered.")
BookCollection.create(title: 'Looking for Bongo', author: 'Eric Velasquez', subject: 'Latinx', image: 'https://images2.penguinrandomhouse.com/cover/9780823437672', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780823437672", description: "Where could Bongo be? Help a young boy find his beloved toy—and figure out how he got lost to begin with.")
BookCollection.create(title: 'My Papi Has a Motorcycle', author: 'Isabel Quintero', subject: 'Latinx', image: 'https://images2.penguinrandomhouse.com/cover/9780525553410', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780525553410", description: "A celebration of the love between a father and daughter, and of a vibrant immigrant neighborhood, by an award-winning author and illustrator duo.")
BookCollection.create(title: "Rudas: Nino's Horrendous Hermanitas", author: 'Yuyi Morales', subject: 'Latinx', image: 'https://mpd-biblio-covers.imgix.net/9781626722408.jpg?w=900', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781250143365", description: "In this picture book, a companion to the Pura Belpré Medalist Niño Wrestles the World, Niño's little sisters get in on the wrestling action.")
BookCollection.create(title: 'Tito Puente: Mambo King', author: 'Monica Brown', subject: 'Latinx', image: 'https://embed.cdn.pais.scholastic.com/v1/channels/sso/products/identifiers/isbn/9780545858847/primary/renditions/700', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780061227837", description: "In this vibrant bilingual picture book biography of musician Tito Puente, readers will dance along to the beat of the mambo king's life.")
BookCollection.create(title: 'Roses for Isabella', author: 'Diana Cohn', subject: 'Latinx', image: 'https://img.thriftbooks.com/api/images/m/1a627242810f990c52ebe61e5bf1027b331a205c.jpg', banned: false, link: "https://www.amazon.com/Roses-Isabella-Diana-Cohn/dp/0880107316/ref=sr_1_1?crid=151RGFXZO1NO4&keywords=Roses+for+Isabella+diane&qid=1666655484&sprefix=roses+for+isabella+diane%2Caps%2C88&sr=8-1", description: "Click I want it to learn more!")
BookCollection.create(title: 'The Librarian of Basra: A True Story from Iraq', author: 'Jeanette Winter', subject: 'Middle Eastern', image: 'https://prodimage.images-bn.com/lf?set=key%5Bresolve.pixelRatio%5D,value%5B1%5D&set=key%5Bresolve.width%5D,value%5B600%5D&set=key%5Bresolve.height%5D,value%5B10000%5D&set=key%5Bresolve.imageFit%5D,value%5Bcontainerwidth%5D&set=key%5Bresolve.allowImageUpscaling%5D,value%5B0%5D&set=key%5Bresolve.format%5D,value%5Bwebp%5D&source=url%5Bhttps://prodimage.images-bn.com/pimages/9780358141839_p0_v5_s600x595.jpg%5D&scale=options%5Blimit%5D,size%5B600x10000%5D&sink=format%5Bwebp%5D', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780358141839", description: "Alia Muhammad Baker’s library in Basra, Iraq, has been a meeting place for those who love books for the past fourteen years. Now war has come, and Alia fears that the library—along with the thirty thousand books within it—will be destroyed forever.")
BookCollection.create(title: 'The Stars in My Geddoh’s Sky', author: 'Claire Sidhom Matze', subject: 'Middle Eastern', image: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51HVV4YGSNL._SX365_BO1,204,203,200_.jpg', banned: false, link: "https://www.amazon.com/Stars-Geddohs-Concept-Albert-Whitman/dp/0807553328/ref=sr_1_1?crid=1CI759BWT6S5Y&keywords=The+Stars+in+My+Geddoh%E2%80%99s+Sky&qid=1666655566&qu=eyJxc2MiOiItMC4wMSIsInFzYSI6IjAuMDAiLCJxc3AiOiIwLjAwIn0%3D&sprefix=the+stars+in+my+geddoh+s+sky%2Caps%2C74&sr=8-1", description: "When Alex' grandfather (Geddoh) comes for a visit from the Middle East, he brings with him presents and stories of his homeland that bring the two closer together, and when he prepares to leave, Alex's Geddoh gives him one special gift that the two can share for a lifetime.")
BookCollection.create(title: 'Snow in Jerusalem', author: 'Deborah Da Costa', subject: 'Middle Eastern', image: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71lMS-mBAIL._AC_UY218_.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780807575253", description: "Avi and Hamudi are two boys who live in Jerusalem's Old City--Avi in the Jewish Quarter and Hamudi in the Muslim Quarter. To each boy, the other's neighborhood is an alien land. Both are caring for the same beautiful white stray cat.")
BookCollection.create(title: 'My Father’s Shop', author: 'Satomi Ichikawa', subject: 'Middle Eastern', image: 'https://d3myrwj42s63no.cloudfront.net/300/192/913/299/9/1929132999.jpg', banned: false, link: "https://www.amazon.com/My-Fathers-Shop-Satomi-Ichikawa/dp/1929132999/ref=sr_1_1?crid=2AZ9BUF46P1YS&keywords=My+Father%E2%80%99s+Shop&qid=1666655627&qu=eyJxc2MiOiIwLjAwIiwicXNhIjoiMC4wMCIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=my+father+s+shop%2Caps%2C82&sr=8-1", description: "Click I want it to learn more!")
BookCollection.create(title: 'Lailah’s Lunchbox: A Ramadan Story', author: 'Reem Faruqi', subject: 'Middle Eastern', image: 'https://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=0884484319&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=pragmom01-20', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780884484318", description: "Lailah is in a new school in a new country, thousands of miles from her old home, and missing her old friends. When Ramadan begins, she is excited that she is finally old enough to participate in the fasting but worried that her classmates won’t understand why she doesn’t join them in the lunchroom.")
BookCollection.create(title: "Yuvi's Candy Tree", author: 'Lesley Simpson', subject: 'Middle Eastern', image: 'https://pjlibrary.org/PJLibrary/media/PJ-Library/books/yuvis-candy-tree.png', banned: false, link: "https://www.amazon.com/Yuvis-Candy-Israel-Lesley-Simpson-ebook/dp/B00J52FNX8/ref=sr_1_1?crid=HQ1FPV4A05T2&keywords=Yuvi%27s+Candy+Tree&qid=1666655697&qu=eyJxc2MiOiIxLjU0IiwicXNhIjoiMS41MCIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=yuvi%27s+candy+tree%2Caps%2C83&sr=8-1", description: "Click I want it to learn more!")
BookCollection.create(title: 'Love Makes a Family', author: 'Sophie Beer', subject: 'Families', image: 'https://images.randomhouse.com/cover/9780525554226', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780525554226", description: "This fun, inclusive board book celebrates the one thing that makes every family a family . . . and that's LOVE.")
BookCollection.create(title: 'Donovan’s Big Day', author: 'Leslea Newman', subject: 'Families', image: 'https://s18670.pcdn.co/wp-content/uploads/Donovans-Big-Day.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781582463322", description: "Donovan's two moms are getting married, and he can't wait for the celebration to begin. After all, as ringbearer, he has a very important job to do. Any boy or girl with same-sex parents—or who knows a same-sex couple—will appreciate this picture book about love, family, and marriage.  The story captures the joy and excitement of a wedding day while the illustrations show the happy occasion from a child's point of view.")
BookCollection.create(title: 'The Great Big Book of Families', author: 'Mary Hoffman', subject: 'Families', image: 'https://images4.penguinrandomhouse.com/cover/9780803735163', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780803735163", description: "This fun and fascinating treasury features all kinds of families and their lives together. ")
BookCollection.create(title: 'One Family', author: 'George Shannon', subject: 'Families', image: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/517rmrZiJkL.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780374300036", description: "A celebration of diverse families plus a clever 1-10 counting element in this unabridged board book edition of One Family.")
BookCollection.create(title: 'Mixed Me!', author: 'Taye Diggs', subject: 'Families', image: 'https://media.theeverymom.com/wp-content/uploads/2018/10/the-everymom-family-books-20.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781250047199", description: "Mike has awesome hair. He has LOTS of energy! His parents love him. And Mike is a PERFECT blend of the two of them. Still, Mike has to answer LOTS of questions about being mixed. And he does, with LOTS of energy and joy in this charming story about a day in the life of a mixed-race child.")
BookCollection.create(title: 'Do You Sing Twinkle?', author: 'Sandra Levins', subject: 'Families', image: 'https://media.theeverymom.com/wp-content/uploads/2018/10/the-everymom-family-books-19.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781433805516", description: "Living apart from a parent can be a hard adjustment for kids. And, if that parent remarries and has stepchildren, things can get really confusing. Told from a young boy's point of view, this book addresses many feelings and questions that children may have while adjusting to remarriage and a blended family after their parents' divorce.")
BookCollection.create(title: 'Over the Moon', author: 'Karen Katz', subject: 'Families', image: 'https://media.theeverymom.com/wp-content/uploads/2018/10/the-everymom-family-books-6.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780805067071", description: "An affirming story about international adoption, based on the author's own experience with her daughter.")
BookCollection.create(title: 'Love Is A Family', author: 'Roma Downey', subject: 'Families', image: 'https://media.theeverymom.com/wp-content/uploads/2018/10/the-everymom-family-books-10.jpg', banned: false, link: "https://www.amazon.com/Love-Family-Roma-Downey/dp/0060393742/ref=sr_1_1?crid=3S9FFPHKUWUHC&keywords=love+is+a+family+roma+downey&qid=1666655967&qu=eyJxc2MiOiIxLjM4IiwicXNhIjoiMS41MSIsInFzcCI6IjEuNTYifQ%3D%3D&sprefix=Love+Is+A+Family+%2Caps%2C79&sr=8-1", description: "Roma Downey, star of the heartwarming television series Touched by an Angel, has a beautiful message for all families.'Sometimes I wish I had sisters, or a dad who lived with me, or at least a brother or something! said Lily.'")
BookCollection.create(title: 'Stella Brings the Family', author: 'Miriam B. Schiffer', subject: 'Families', image: 'https://media.theeverymom.com/wp-content/uploads/2018/10/the-everymom-family-books-14.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781452111902", description: "Stella's class is having a Mother's Day celebration, but what's a girl with two daddies to do? It's not that she doesn't have someone who helps her with her homework, or tucks her in at night. Stella has her Papa and Daddy who take care of her, and a whole gaggle of other loved ones who make her feel special and supported every day. She just doesn't have a mom to invite to the party. Fortunately, Stella finds a unique solution to her party problem in this sweet story about love, acceptance, and the true meaning of family.")
BookCollection.create(title: 'Our Skin: A First Conversation About Race', author: 'Megan Madison & Jessica Ralli', subject: 'Social Justice', image: 'https://images4.penguinrandomhouse.com/cover/9780593519394', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780593382639", description: "Based on the research that race, gender, consent, and body positivity should be discussed with toddlers on up, this read-aloud board book series offers adults the opportunity to begin important conversations with young children in an informed, safe, and supported way.")
BookCollection.create(title: 'Peaceful Fights for Equal Rights', author: 'Rob Sanders', subject: 'Social Justice', image: 'https://www.booksourcebanter.com/wp-content/uploads/Peaceful-Fights-for-Equal-Rights-497x500.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781534429437", description: "A primer for peaceful protest, resistance, and activism from the author of Rodzilla and Pride: The Story of Harvey Milk and the Rainbow Flag.")
BookCollection.create(title: 'Rise Up! The Art of Protest', author: 'Jo Rippon', subject: 'Social Justice', image: 'https://www.booksourcebanter.com/wp-content/uploads/Rise-Up-416x500.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781623541507", description: "Celebrate the right to resist!")
BookCollection.create(title: 'Voices of Justice: Poems About People Working for A Better World', author: 'George Ella Lyon', subject: 'Social Justice', image: 'https://www.booksourcebanter.com/wp-content/uploads/Voices-of-Justice-410x500.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781250263209", description: "A bold, lyrical collection of poems that highlight some of the most celebrated activists from around the world and throughout history.")
BookCollection.create(title: 'Antiracist Baby', author: 'Ibram X. Kendi', subject: 'Social Justice', image: 'https://images.squarespace-cdn.com/content/v1/6036bf6d46a72e136be8eee1/1614296752705-B9TFPMBKJ04G12BSHDXC/Antiracist+Baby.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780593110416", description: "From the National Book Award-winning author of Stamped from the Beginning and How to Be an Antiracist comes a fresh new board book that empowers parents and children to uproot racism in our society and in ourselves.")
BookCollection.create(title: 'Change Sings', author: 'Amanda Gorman', subject: 'Social Justice', image: 'https://images4.penguinrandomhouse.com/cover/9780593203224', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9780593203224", description: "A lyrical picture book debut from #1 New York Times bestselling author and presidential inaugural poet Amanda Gorman and #1 New York Times bestselling illustrator Loren Long")
BookCollection.create(title: "Woke: A Young Poet's Call to Justice", author: 'Mahogany L. Browne with Elizabeth Acevedo & Olivia Gatwood', subject: 'Social Justice', image: 'https://mpd-biblio-covers.imgix.net/9781250311207.jpg?w=900', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781250311207", description: "Woke: A Young Poet's Guide to Justice is a collection of poems to inspire kids to stay woke and become a new generation of activists.")
BookCollection.create(title: 'We Shall Overcome: The Story of a Song', author: 'Debbie Levy', subject: 'Social Justice', image: 'https://images.squarespace-cdn.com/content/v1/5f29b0069d47f939f090dd87/1597689250580-00Z970G7XJI7LU0UX13X/WSO+from+LBYR.jpg?format=500w', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781423119548", description: "It only takes a few words to create change. It only takes a few people to believe that change is possible. And when those people sing out, they can change the world. 'We Shall Overcome' is one of their songs.")
BookCollection.create(title: 'Grandfather Gandhi', author: 'Arun Gandhi & Bethany Hegedus', subject: 'Social Justice', image: 'https://www.rebekahgienapp.com/wp-content/uploads/2017/01/grandfather_gandhi.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781442423657", description: "Mahatma Gandhi’s grandson tells the story of how his grandfather taught him to turn darkness into light in this uniquely personal and vibrantly illustrated tale that carries a message of peace.")
BookCollection.create(title: 'Separate Is Never Equal: Sylvia Mendez and Her Family’s Fight for Desegregation', author: 'Duncan Tonatiuh', subject: 'Social Justice', image: 'https://www.rebekahgienapp.com/wp-content/uploads/2017/01/separate_never_equal.jpg', banned: false, link: "https://cafeconlibrosbooks.indielite.org/book/9781419710544", description: "Seven years before Brown v. Board of Education, the Mendez family fought to end segregation in California schools. Discover their incredible story in this picture book from award-winning creator Duncan Tonatiuh.")

puts 'book collection seeded'

puts 'seeding user books'

# 35.times do
#     UserBook.create(
#         rating: rand(1..5),
#         user_id: User.all.sample.id,
#         book_collection_id: BookCollection.all.sample.id,
#         discussion_questions: Faker::Lorem.sentence,
#         student_anecdotes: Faker::Lorem.sentence
#     )
# end

puts 'user books seeded'

puts 'seeding follows'

35.times do
    Follow.create(
        follower_id: User.all.sample.id,
        followee_id: User.all.sample.id
    )
end

puts 'follows seeded'

